### PR TITLE
[fix] Remove unnecessary words in mailto

### PR DESCRIPTION
**Pull request by rikoroku**
I writed my mail address(`hogehoge@example.com`) to `email` of `config.toml`.

After, I saw a wrong mail address  `hogeh-remove-oge@example.com` when I click the email address in about page.

So, I made this PR.

Please checking this..!

### CODE REVIEW

**Comment by JulienRouse** [comment]
It is on purpose (I believe), it is to avoid being spammed by having your real mail adress on the open.

**Comment by rikoroku** [comment]
Thanks for your comment.
I understand the purpose.
And I'll close this PR, Beause My PR was already has been questioned and solved https://github.com/eddiewebb/hugo-resume/issues/26.

**Comment by JulienRouse** [comment]
If you don't want to have a email that people have to fix themselves, I saw website using an image of their mail instead of text. The downside it that you can't copy paste it but it should avoid most of the spam.

**Comment by rikoroku** [comment]
@JulienRouse 
That makes sense. 
But I can't do your idea because I like the current icon layout of hugo-resume.
Thanks for your advice.

**Pull request closed without merging**
